cpu = 2

[app]
  contractAddress    = ""

[db]
  projectId = "marine-dev"

[ethereum]
  endpoint = "https://ropsten.infura.io/v3/21a0bbd84cf24419be9b457e6399e15d"

[storage]
  storageBucket = "marine-dev.appspot.com"
